[package]
name = "gotenberg_pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["multipart"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
bytes = "1.0"
serde_json = "1.0"
