name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Step to spin up the Gotenberg Docker container
    - name: Start Gotenberg Docker container
      run: docker run -d -p 3000:3000 gotenberg/gotenberg:8

    # Step to wait for any HTTP response from Gotenberg
    - name: Check Gotenberg container is reachable
      run: |
        for i in {1..10}; do
          if curl --silent --head --fail http://localhost:3000/; then
            echo "Gotenberg is reachable!";
            exit 0;
          fi
          echo "Waiting for Gotenberg...";
          sleep 3;
        done
        echo "Failed to reach Gotenberg";
        exit 1

    - name: Run tests
      run: cargo test --verbose
