on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Step to spin up the Gotenberg Docker container
    - name: Start Gotenberg Docker container
      run: docker run -d -p 3000:3000 gotenberg/gotenberg:8
      
    # Step to wait for the container to be ready (optional, ensure the service is up)
    - name: Wait for Gotenberg to be ready
      run: |
        for i in {1..10}; do
          if curl --silent http://localhost:3000/ | grep -q "OK"; then
            echo "Gotenberg is ready!";
            exit 0;
          fi
          echo "Waiting for Gotenberg...";
          sleep 3;
        done
        echo "Gotenberg failed to start";
        exit 1

    - name: Run tests
      run: cargo test --verbose
